
>
> Put in your css file or directly in rmarkdown

<style>
  .column {
    columns: 2 300px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 300px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }

  }
</style>

___
>
🤨 здравствуйте Как получить виртуальную карту?

:::row:::
:::column:::

🧑‍💼 Human

<small>💬 message</small>

     Здравствуйте! Чем я могу Вам помочь? Просьба подождать несколько минут. Спасибо за ожидание. В связи с особенностями банковского законодательства и правилами международных платежных систем, на данный момент.  мы не можем предложить резидентам стран вне ЕЭЗ выпустить платёжную карту ( в виртуальном и пластиковом виде ). Однако, одним из наших актуальных приоритетов является решение этой проблемы и получение необходимых разрешений. Мы проинформируем Вас как только заказ карт для клиентов из Вашей страны станет доступен. Вам доступен счёт в формате европейского IBAN – это счета для получения и отправки платежей в зоне SEPA (Единая Зона Платежей в Евро). Также Вам доступен интегрированный криптовалютный сервис от наших партнеров. Вы можете использовать его для покупки и продажи криптовалюты, а также для пополнения и вывода денежных средств Вашего счета в Blackcatcard. С более подробной информацией по данному сервису Вы можете ознакомиться на сайте наших партнёров https://www.maner.io// Есть ли у Вас ещё вопросы, на которые я могу ответить в данный момент? Если у Вас возникнут ещё вопросы, пишите нам в любое время! Хорошего дня!
    :::column-end:::
    :::column:::
🧠  GPT
     <small>💬 message</small>

Virtual card is created immediately after successful registration and you can start using it. The virtual card allows for all operations except for offline purchases (using a POS terminal) and cash withdrawals from ATM. The virtual card is activated automatically after successful registration.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

"The virtual card is created immediately after successful registration and you can start using it. With the virtual card, all operations are possible except for offline purchases (using a POS terminal) and cash withdrawals from ATM. Virtual card is activated automatically after successful registration"【7†source】.

> ACTIONS

- No further actions required.

> SELFSCORING

★★★★★★★★★☆
<small> >>> Virtual card is created immediately after successful registration and you can start using it. With virtual card all operations are possible except for offline purchases (using a POS terminal) and cash withdrawals from ATM.

# 【1†Knowledge.docx†file-xzKdLMm3oLtV0K3WrTYzVyCA】

Standard delivery by simple letter is up to 15 business days to EU countries and up to 20 business days to other countries." Cards Main сard/Основная карта 4. Do I have to activate my Main card? "Virtual card is activated automatically after successful registration. To activate a plastic card after receiving it you need to click on the picture of the card. A tab will open with the button: ""Activate card"". Click on this button
</small>

:::column-end:::
:::row-end:::

___
> 🤬 добрый вечер подскажите - пытаюсь сделать перевод по карте. перевожу на карту виза Испания. когда ввожу номер карты - выдает ошибку не верный номер карты. но ошибок в номере нет

:::row:::
:::column:::

🧑‍💼 Human

<small>💬 message</small>

     Добрый вечер! Чем я могу Вам помочь? Please, wait a few minutes in the chat. Извините за предыдущее сообщение. Пожалуйста, подождите несколько минут в чате. Спасибо за ожидание! Переводы на карту возможны только между владельцами Blackcatcard, в другие банки переводы по номеру карты недоступны. Вы можете сделать SEPA перевод. Это платежные перечисления в валюте евро, осуществляемые между всеми странами ЕЭЗ (Австрия, Бельгия, Болгария, Венгрия, Германия, Греция, Дания, Ирландия, Исландия, Испания, Италия, Кипр, Латвия, Литва, Лихтенштейн, Люксембург, Мальта, Нидерланды, Норвегия, Польша, Португалия, Румыния, Словакия, Словения, Финляндия, Франция, Хорватия, Чехия, Швеция, Эстония), а также Андоррой, Великобританией, Монако, Сан-Марино и Швейцарией. Перечисления возможны со счетов в формате IBAN; срочность перечисления - стандартная.
    :::column-end:::
    :::column:::
🧠  GPT
     <small>💬 message</small>

Для решения проблемы с ошибкой при вводе номера карты просим вас обратить внимание на системные уведомления и корректно заполнить поля, выделенные красным цветом.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

Используемый фрагмент из базы знаний: "Read system alerts. Correct the values in the fields highlighted in red"【9†source】.

> ACTIONS

- request data from the client (specify what): Просьба предоставить точное описание ошибки, которое появляется при вводе номера карты, чтобы мы могли вам помочь.

> SELFSCORING

★★★★★★★★☆☆
<small> >>> I receive errors when filling in the payment fields. What should I do? Read system alerts. Correct the values in the fields highlighted in red
</small>

:::column-end:::
:::row-end:::

___
> 😤 Hello  can i use the card in the app menu as a virtual card

:::row:::
:::column:::

🧑‍💼 Human

<small>💬 message</small>

     Hello! Please specify last 4 digits of the card.
    :::column-end:::
    :::column:::
🧠  GPT
     <small>💬 message</small>

The card displayed within the app menu can be used as a virtual card for all transactions excluding purchases in physical stores or cash withdrawals at ATMs.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

"The virtual card can be used for all transactions except for purchases in the stores or cash withdrawals in the ATM."【7†source】.

> ACTIONS

- No further action required.

> SELFSCORING

★★★★★★★★☆☆
<small> >>> The virtual card can be used for all transactions except for purchases in the stores or cash withdrawals in the ATM
</small>

:::column-end:::
:::row-end:::

___
> 🤨 can i use my card with iphone before it has arrived

:::row:::
:::column:::

🧑‍💼 Human
<small>💬 message</small>

     Hello! Please specify last 4 digits of the card.
    :::column-end:::
    :::column:::
<gray>🧠  GPT</gray>
     <right><small>💬 message</small></right>

You can start using the virtual card feature automatically after successful registration in the BlackCatCard mobile application. While you wait for the arrival of the plastic card, the virtual card is fully functional and can be used for online purchases and other transactions where a physical card is not required.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

The information is based on the premise that a virtual card is activated automatically upon successful registration【9†source】.

> ACTIONS

No further actions are required at this time.

> SELFSCORING

★★★★★★★★☆☆
<small> >>> Virtual card is activated automatically after successful registration. To activate a plastic card after receiving it you need to click on the picture of the card. A tab will open with the button: ""Activate card"". Click on this button.
BCC app: Next by entering your PIN code for authorization confirm the card's activation.
Gekkard I-bank: Next you will receive on your phone an SMS with an activation code. Enter the code in the window that opens.
Sign this card on the back side."
Cards Preissued сard/Предвыпущенная карта 1. What is a preissued Blackcatcard card? "This is a Blackcatcard card without a name of the cardholder indicated on it. The card is handed to the customer prior the registration in the system but it's usage at this step is impossible. In order for the card to become available for use it is necessary to download the mobile app register and being verified after which it will be possible to use the card.
Please note that the functionality of the payment card is available only for the customers who indicated during the registration and confirmed their residential address in one of the EEA countries."
Cards Preissued сard/Предвыпущенная карта 2. Can I register with a preissued card and open an account with functionality of payment card if I am not an EEA resident? No as the functionality of the payment card is available only for the residents of one of the EEA countries. In order to open an account with functionality of payment card you need to indicate during the registration an address in one of the EEA countries and confirm this address with documents.
Cards Preissued сard/Предвыпущенная карта 3. I received a preissued card. On which step of registration should I enter the card data? "When registering after being acquainted with the legal agreements and confirming your phone number you will be redirected to the next step where you need to choose one of two options: ""Register and get Blackcatcard by mail"" or ""Just register. I've got the card already."" Choose the second option if you have a preissued card. On the following page you will be asked to enter the card's number. Enter it to proceed to the next step of registration."
Cards Preissued сard/Предвыпущенная карта 4. What is the difference between a card issued after registration and a preissued one? "Main differences are the following:

- A preissued plastic card is handed to the customer prior the registration in the system. After successful registration and activation of the card its functionality becomes available for purchases in the stores and cash withdrawals. During the regular registration the client needs to wait for the issue and delivery of a plastic card to his region only after which he will be able to use the plastic card functionality;
- A preissued card contains no name of the cardholder indicated on it. During the regular registration the name on the card will be displayed as it was indicated by the customer during the registration. "
  Cards Preissued сard/Предвыпущенная карта 5. After registering with preissued card will I be able to make online purchases? Yes of course. Virtual card is activated automatically after successful registration
  </small>

:::column-end:::
:::row-end:::

___
> 😤 hello i want to change my phone number actual phone number +33757509605 i want to change for +33757842559 thanks

:::row:::
:::column:::

🧑‍💼 Human

<small>💬 message</small>

     Hello! Please, hold on for several minutes. Thank you for waiting. Dear customer, we want to inform you that when changing the phone number, you might be requested to provide additional documents, and the existing correspondence with the financial institution, along with your personal templates, will be lost. After changing the phone number, you will begin receiving SMS to enter the app and confirm operations to the new number. Please note that changing the phone number may cause slight problems in receiving the SMS intended for authorization. This may happen due to possible issues on the electronic service providers' side, whose systems we use to send those SMS. Do you agree to continue the phone number change procedure?
    :::column-end:::
    :::column:::
🧠  GPT
     <small>💬 message</small>

To update your phone number, please follow these steps: Select your country and enter your new mobile phone number without the country code, as it will be automatically set when you select your country. Then click on the "Next" button to proceed.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

To proceed with such a request, the following content from the knowledge base is applicable: "How to indicate the phone number? Select your country and enter your mobile phone number. Please note that the country code will be automatically set when you select your country so the phone number must be entered without the country code. Then click on the 'Next' button."【9†source】.

> ACTIONS

- request data from the client (please provide your full name and the old phone number for verification)
- refer the question to a specialist to assist with changing the phone number

> SELFSCORING

★★★★★★★★☆☆
<small> >>> How to indicate the phone number? "Select your country and enter your mobile phone number. Please note that the country code will be automatically set when you select your country so the phone number must be entered without the country code. Then click on the ""Next"" button. "
Registration Authorization data and status 10. How to continue the incomplete registration? "After entering the SMS code click on the ""Continue registration"" button and follow the on-screen instructions."
Registration Authorization data and status 11. After entering the code from SMS a new screen opens where I have to select one of two options: «Register and get Blackcatcard per mail» or «Just register I’ve got the card already». What should I choose? "Choose the second option if you have a preissued card. On the following page you will be asked to enter the card's number. If you don’t have preissued card then choose the first option.
Please note that the functionality of the payment card is available only for the customers who indicated during the registration and confirmed their residential address in one of the EEA countries."
Registration Authorization data and status "12. Why do I get a ""The phone number does not match with authentication token phone"" error during the registration/authorization?" Please check that your phone number is entered correctly. You may have put an extra 0 (zero) between the country code and your number when entering your phone number.
Registration Authorization data and status 13. I can’t request a code for registration (the technical number is highlighted in red/is not sent). Customer indicated Yemen's phone number (+96
</small>

:::column-end:::
:::row-end:::

___
> 😤 здравствуйте у меня возникла проблема я хотел бы изменить номер так как уезжаю за границу я могу это сделать для пользования приложениям?

:::row:::
:::column:::

🧑‍💼 Human

<small>💬 message</small>

     Здравствуйте! Вы можете сменить номер телефона, привязанный к Вашему счету. Пожалуйста, подождите несколько минут в чате. Спасибо за ожидание. Хотим проинформировать, что при смене номера телефона у Вас могут быть запрошены дополнительные документы, а имеющаяся переписка с финансовым учреждением и шаблоны будут утеряны. После смены номера телефона, СМС для входа в приложение и подтверждения операций будут приходить уже на новый номер телефона. Обращаем Ваше внимание, что после смены номера телефона возможны проблемы, связанные с получением СМС для авторизации, ввиду неполадок на стороне независимых от нас сервисов электронных провайдеров, чьей системой мы пользуемся для отправления данных СМС. Вы согласны продолжить процедуру смены номера телефона?
    :::column-end:::
    :::column:::
🧠  GPT
     <small>💬 message</small>

Для изменения номера телефона, пожалуйста, используйте номер мобильного оператора другой страны для регистрации, после чего вы сможете изменить его на предпочитаемый номер.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

Как указано в нашей базе знаний, номера телефонов определенных стран могут столкнуться с ограничениями относительно SMS-уведомлений от поставщиков услуг, которые мы используем. После успешной регистрации номер телефона можно будет изменить【9†source】.

> ACTIONS

- request data from the client (после регистрации запросить у клиента предпочитаемый номер для изменения)

> SELFSCORING

★★★★★★★★☆☆
<small> >>> 13. I can’t request a code for registration (the technical number is highlighted in red/is not sent). Customer indicated Yemen's phone number (+967...) Since phone numbers of Yemeni telecom operators are subject to restrictions on receiving SMS from the providers whose services we use SMS delivery with a one-time confirmation code cannot be carried out. In this case we recommend that you use the phone number of a mobile operator of another country. After successful registration you can change your number to the number of a Yemeni telecom operator
</small>

:::column-end:::
:::row-end:::

___
> 🤨 hello there is a red message card is blocked by bank

:::row:::
:::column:::

🧑‍💼 Human

<small>💬 message</small>

     Hello! Please, specify the 4 last digits of the card.
    :::column-end:::
    :::column:::
🧠  GPT
     <small>💬 message</small>

To address the issue of your blocked card, please provide the last 4 digits of the blocked card number.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

"How do I unblock a card? The card is blocked by the bank. You cannot unblock the card yourself. Please specify the last 4 digits of the blocked card number."【9†source】

> ACTIONS

- request data from the client (specify the last 4 digits of the blocked card number)

> SELFSCORING

★★★★★★★★☆☆
<small> >>> How do I unblock a card? The card is blocked by the bank. You cannot unblock the card yourself. Please specify the last 4 digits of the blocked card number
</small>

:::column-end:::
:::row-end:::

___
> 🤨 Good afternoon

some doubts on expenses recorded; on 02/01 700€ charged on card, up to today expenses for about 130€, found remaining 29,59€
there’s something strange, may I have an explanation?
Thanks

:::row:::
:::column:::

🧑‍💼 Human

<small>💬 message</small>

     Dear customer, At the moment, our product is in high demand among existing and potential customers. Therefore, the reply may take up to 4 hours. We apologize for the inconvenience caused and thank you for understanding! Hello! Please, wait a few minutes. We thank you for waiting and being patient. Some questions take a little longer to be resolved. Please wait for our message. We will get back to you with the result as soon as we resolve your issue. Thank you for waiting. Dear customer, some transactions made with a payment card may not be displayed in the transaction history until we receive confirmation from the payment system for these transactions. As soon as we receive confirmation, you will see the needed transaction in the transaction history and you will be able to verify incoming and outgoing transactions and check the correctness of the displayed balance. May I assist you with anything else at the moment? In case you have further questions or requests, please contact us – we’ll be glad to help you. Have a nice day!
    :::column-end:::
    :::column:::
🧠  GPT
     <small>💬 message</small>

To clarify your expenses, on 02/01 a charge of 700€ was made on your card. Including the current expenses which total approximately 130€, your remaining balance seems to be 29,59€. It is important to ensure that all transactions including charges, refunds, and pending transactions are accounted for. To fully understand the discrepancy, I suggest a review of your account's transaction history to track all activity that has affected your balance.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

[Transactions taken into account for calculating expenses include purchases made in online stores and in walk-in stores, where payment is made using card details or a plastic card【11†source】].

> ACTIONS

- Obtain data from the banking system to review the monthly transactions for a detailed account statement which will clarify the expenses and current balance.
- Request data from the client to confirm the dates and amounts of the transactions in question for a precise investigation.

> SELFSCORING

★★★★★★★★☆☆
<small> >>> 08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." On what amount does my referral has to top-up their account with Binance Pay for me to receive the bonus? The account must be topped up in an amount of at least 30 euros total.
Adv campaign and mass mailing to customers Adv campaign "08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." What bonus will I get for registering a referral with my promo code? "According to the new terms of the referral program from November 8 2021 you as the agent are not entitled to a bonus for registering a referral using your promo code.
But you have the opportunity to receive a bonus in the amount of 35 euros for each of your referrals which will participate in the bonus program and make purchases with a card in the amount of at least 1000 euros within 2 (two) months after accepting the terms of the program.
Please draw your attention that only your referral to whom the payment card has been opened can participate in the program. At the moment payment cards can only be opened for residents of EEA. "
Adv campaign and mass mailing to customers Adv campaign "08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." What bonus will I receive if I wouldn’t be able to spend 1000 euros in 2 months? In order to receive a bonus of 40 euros you need to make purchases with a card amounting to at least 1000 euros within 2 months after the start of participation in the program. Unfortunately if this condition is not met you will not be able to receive the bonus.
Adv campaign and mass mailing to customers Adv campaign "08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." What bonus will I receive if my referral did not manage to make purchases for 1000 euros in 2 months? Unfortunately you will not be able to receive a bonus if your referral has not fulfilled all the conditions of the referral program from the first time.
Adv campaign and mass mailing to customers Adv campaign "08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." What conditions should I follow to receive a bonus in the amount of 40 euro? You must be subscribed to the loyalty program and spend at least EUR 1000 from your account on purchases in walk-in stores and/or online stores within 2 (two months) from the date you confirm your participation.
Adv campaign and mass mailing to customers Adv campaign "08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." What conditions should I follow to receive a bonus in the amount of 40 euro? When calculating EUR 1000 expense we don't count internal and external money transfers; withdrawing cash from ATMs cash registers and any other retail outlets; operations with cryptocurrency; other cards top-ups using Blackcatcard fee for top up made from another card and the conversion margin on purchases/cash withdrawal made in local currency.
Adv campaign and mass mailing to customers Adv campaign "08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." What do I need to do to get a promo code for inviting a friend? Customers who have an active account and are connected to one of the loyalty programs automatically receive a newsletter to invite friends.
Adv campaign and mass mailing to customers Adv campaign "08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." What transactions are not taken into account when calculating the EUR 1000 expense? When calculating EUR 1000 expense we don't count internal and external money transfers; withdrawing cash from ATMs cash registers and any other retail outlets; operations with cryptocurrency; other cards top-ups using Blackcatcard fees and conversion margins.
Adv campaign and mass mailing to customers Adv campaign "08.11.2021 ""Refer a friend to Blackcatcard and you can both earn 30 35 or 45 EUR""." What transactions are taken into account when calculating the EUR 1000 expense? "When calculating EUR 1000 expense we count purchases made in online stores and in walk-in stores i.e. those operations where you pay using your payment card details or a plastic card
</small>

:::column-end:::
:::row-end:::

___
> 🤨 hello, can I close my account ?

:::row:::
:::column:::

🧑‍💼 Human

<small>💬 message</small>

     Hello. Yes, for sure. Please hold on for a while. We kindly thank you for waiting. Dear customer, we would like to inform you that closing the account will automatically close all your cards. We kindly ask you to check the balance of your crypto wallet and withdraw or sell cryptocurrency if there is any available. Please notify us as soon as your crypto wallet balance is zero, so we will be able to proceed with the account closing procedure. Dear customer, since I haven't heard back from you in some time, I am going to close this chat. Please message us whenever it is convenient for you. We will be waiting for your response! Have a nice day!
    :::column-end:::
    :::column:::
🧠  GPT
     <small>💬 message</small>

You can close your account at any time, and there is no fee for account closure.

<small>🛠️ KNOWLEDGE tuning \(скрипты\)</small>

"What is the fee for account closure? There is no fee for account closure."【9†source】.

> ACTIONS

- request data from the client (specify the reason for account closure)
- refer the question to a specialist to proceed with the account closure

> SELFSCORING

★★★★★★★★☆☆
<small> >>> What is the fee for account closure? There is no fee for account closure
</small>

:::column-end:::
:::row-end:::

___
> 🤬 Добрый день! ответила на запрос по документам по электронной почте. Надеюсь на быстрое решение вопроса с зачислением средств на мой счет

<!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=false} -->
